### PR TITLE
Fixes of various outstanding items after merge with upstream

### LINKED ISSUE #67: Fixes
- [x] `#[pallet::unbounded]` used on all storage items which used unbounded vectors. This was to reduce the complexity of the update to latest and another issue should be created to tackle.
- [X] Used `bounded_*()` helper functions for Dao tests, but only as a wrapper until the pallet can be fully migrated to bounded vecs.
- [x] assess public visibility of helper functions in `dao` pallet
- [x] ensure that usage of `into_account_truncating()` is correct within `task` pallet
- [x] set max lengths of new config items of `dao` config in runtime. These are used by the Dao struct and were previously unbounded.
- [x] there were upstream changes to RPC apis (`jsonrpsee`) , need to check that all still works from the front-end. 
- [ x review possible switch to new `list_benchmarks!` and `add_benchmarks!` macros within runtime benchmarks
- [x] Cargo.lock should not be included within source control for library crates (pallets) : [source](https://github.com/rust-lang/cargo/issues/315#issuecomment-634598379)

### PR DESCRIPTION
**Pull request by evilrobot-01**
- Added missing Dao config to runtime
- Moved runtime benchmark definitions to `define_benchmarks`, as per upstream. This allows them to be defined in a single place.
- Removed unnecessary unbounded attribute macros
- Updated cargo.lock with missing `treasury` pallet
- Replaced unbounded vectors in `did` pallet with bounded, removing checks/tests which were no longer necessary
  - Added a bound for delegate type length to config
  - Added the default delegate type to config for definition of value in runtime/mock

### CODE REVIEW

File: pallets/did/src/lib.rs [hunk 1]
```diff
@@ -137,7 +141,7 @@ pub mod pallet {
     #[pallet::storage]
     #[pallet::getter(fn nonce_of)]
     #[pallet::unbounded]
```
Comment (f-gate) [inline pallets/did/src/lib.rs]: a rogue unbounded macros here.

File: pallets/did/src/lib.rs [hunk 2]
```diff
@@ -616,7 +612,7 @@ for Pallet<T>
     }
 
     /// Validates if an attribute belongs to an identity and it has not expired.
-    fn valid_attribute(identity: &T::AccountId, name: &[u8], value: &[u8]) -> DispatchResult {
+    fn valid_attribute(identity: &T::AccountId, name: &BoundedNameOf<T>, value: &BoundedValueOf<T>) -> DispatchResult {
         ensure!(name.len() <= 64, Error::<T>::InvalidAttribute);
```
Comment (f-gate) [inline pallets/did/src/lib.rs]: ensure is perhaps not required but not critical

File: pallets/did/src/tests.rs [hunk 3]
```diff
@@ -85,8 +87,8 @@ fn validate_delegated_claim() {
 #[test]
 fn add_on_chain_and_revoke_off_chain_attribute() {
     new_test_ext().execute_with(|| {
-        let name = b"MyAttribute".to_vec();
-        let mut value = [1, 2, 3].to_vec();
+        let name: BoundedNameOf<Test> = b"MyAttribute".to_vec().try_into().unwrap();
+        let mut value: BoundedValueOf<Test> = bounded_vec![1, 2, 3];
```
Comment (f-gate) [inline pallets/did/src/tests.rs:91]: you can make bounded vecs with a macro! awesome

File: pallets/did/src/tests.rs [hunk 4]
```diff
@@ -41,7 +43,7 @@ fn validate_delegated_claim() {
         System::set_block_number(1);
 
         // Predefined delegate type: "Sr25519VerificationKey2018"
-        let delegate_type = b"x25519VerificationKey2018".to_vec();
```
Comment (stojanov-igor) [inline pallets/did/src/tests.rs:44]: Still don't know what this is?

**Review by stojanov-igor — APPROVED** [review]
Looks good.

Are we fixing all the Clippy warnings? I keep getting the same warnings in reviews, so maybe we should remove them from CI and do occasional clippy fixes?

File: pallets/did/src/tests.rs (hunk 4 above)
Comment (evilrobot-01) [reply pallets/did/src/tests.rs:44]: Afraid not, but I made the value configurable at least now.

**Review by f-gate — APPROVED** [review]
nice

**Comment by evilrobot-01** [comment]
> Looks good.
> 
> Are we fixing all the Clippy warnings? I keep getting the same warnings in reviews, so maybe we should remove them from CI and do occasional clippy fixes?

I fixed a number of them in a previous PR but it seems maybe more have been introduced. At the moment they are just warnings, meaning that it will flag them but someone has to do something about them. This can be set to fail checks, but there are a number of upstream issues which require resolution first unfortunately.

I personally think it may be best to deal with them as part of the review process for now, as I feel items such as unnecessary clones being picked up are worth addressing.

Guess you need to decide on whether its worth the hassle.

File: pallets/did/src/lib.rs (hunk 1 above)
Comment (evilrobot-01) [reply pallets/did/src/lib.rs]: Nice catch, will fix, thanks!

File: pallets/did/src/lib.rs (hunk 2 above)
Comment (evilrobot-01) [reply pallets/did/src/lib.rs]: Nice catch, will remove, thanks!
